import React from 'react';
import AlternativesList from 'components/AlternativesList/AlternativesList.js';

import './ProductDetails.sass';

import nestleLogo from 'assets/nestle.png';


const propsProduct = {
	"product": {
		"code": "0068274000218",
		"name": "Pure Life Bottled Water",
		"product_line": null,
		"BSIN": {
			"code": "8ZJDIE",
			"name": "Nestlé",
			"link": "http://www.nestle.com",
			"img": "http://product.okfn.org.s3.amazonaws.com/images/brand/8ZJDIE.jpg"
		},
		"weight": "",
		"volume": "1 x 500.0 ml / ",
		"alcohol": "",
		"img": "http://product.okfn.org.s3.amazonaws.com/images/gtin/gtin-006/0068274000218.jpg",
		"GPC_S_CD": {
			"code": "50000000",
			"name": "Food/Beverage/Tobacco",
			"img": "http://product.okfn.org.s3.amazonaws.com/images/gpc/50000000.jpg"
		},
		"GPC_F_CD": null,
		"GPC_C_CD": null,
		"GPC_B_CD": null,
		"GCP_CD": {
			"code": "0682740000016",
			"name": "Nestle Waters Canada",
			"address_1": "",
			"address_2": "",
			"address_3": "ON",
			"cp": "N1H 6H9",
			"city": "Guelph",
			"country": "CA"
		}
	},
};
const propsStories = {
	"stories": {
		"kind": "Listing",
		"data": {
			"after": "t3_bdozxx",
			"dist": 10,
			"facets": {},
			"modhash": "",
			"children": [
				{
					"kind": "t3",
					"data": {
						"approved_at_utc": null,
						"subreddit": "AskReddit",
						"selftext": "",
						"author_fullname": "t2_13x9ko",
						"saved": false,
						"mod_reason_title": null,
						"gilded": 0,
						"clicked": false,
						"title": "Who’s the world’s evilest corporation? Why?",
						"link_flair_richtext": [],
						"subreddit_name_prefixed": "r/AskReddit",
						"hidden": false,
						"pwls": 6,
						"link_flair_css_class": null,
						"downs": 0,
						"hide_score": false,
						"name": "t3_a03hq5",
						"quarantine": false,
						"link_flair_text_color": "dark",
						"author_flair_background_color": null,
						"subreddit_type": "public",
						"ups": 4111,
						"total_awards_received": 0,
						"media_embed": {},
						"author_flair_template_id": null,
						"is_original_content": false,
						"user_reports": [],
						"secure_media": null,
						"is_reddit_media_domain": false,
						"is_meta": false,
						"category": null,
						"secure_media_embed": {},
						"link_flair_text": null,
						"can_mod_post": false,
						"score": 4111,
						"approved_by": null,
						"thumbnail": "",
						"edited": false,
						"author_flair_css_class": null,
						"author_flair_richtext": [],
						"gildings": {},
						"content_categories": null,
						"is_self": true,
						"mod_note": null,
						"created": 1543131484,
						"link_flair_type": "text",
						"wls": 6,
						"banned_by": null,
						"author_flair_type": "text",
						"domain": "self.AskReddit",
						"selftext_html": null,
						"likes": null,
						"suggested_sort": null,
						"banned_at_utc": null,
						"view_count": null,
						"archived": false,
						"no_follow": false,
						"is_crosspostable": false,
						"pinned": false,
						"over_18": false,
						"all_awardings": [],
						"media_only": false,
						"can_gild": false,
						"spoiler": false,
						"locked": false,
						"author_flair_text": null,
						"visited": false,
						"num_reports": null,
						"distinguished": null,
						"subreddit_id": "t5_2qh1i",
						"mod_reason_by": null,
						"removal_reason": null,
						"link_flair_background_color": "",
						"id": "a03hq5",
						"is_robot_indexable": true,
						"report_reasons": null,
						"author": "mayhem-182",
						"num_crossposts": 3,
						"num_comments": 2388,
						"send_replies": true,
						"whitelist_status": "all_ads",
						"contest_mode": false,
						"mod_reports": [],
						"author_patreon_flair": false,
						"author_flair_text_color": null,
						"permalink": "/r/AskReddit/comments/a03hq5/whos_the_worlds_evilest_corporation_why/",
						"parent_whitelist_status": "all_ads",
						"stickied": false,
						"url": "https://www.reddit.com/r/AskReddit/comments/a03hq5/whos_the_worlds_evilest_corporation_why/",
						"subreddit_subscribers": 22824959,
						"created_utc": 1543102684,
						"media": null,
						"is_video": false
					}
				},
				{
					"kind": "t3",
					"data": {
						"approved_at_utc": null,
						"subreddit": "AskReddit",
						"selftext": "",
						"author_fullname": "t2_1wdk4ghg",
						"saved": false,
						"mod_reason_title": null,
						"gilded": 2,
						"clicked": false,
						"title": "You can remove 1 big company from the world. Which one do you eliminate and why?",
						"link_flair_richtext": [],
						"subreddit_name_prefixed": "r/AskReddit",
						"hidden": false,
						"pwls": 6,
						"link_flair_css_class": null,
						"downs": 0,
						"hide_score": false,
						"name": "t3_atjc1e",
						"quarantine": false,
						"link_flair_text_color": "dark",
						"author_flair_background_color": null,
						"subreddit_type": "public",
						"ups": 10759,
						"total_awards_received": 3,
						"media_embed": {},
						"author_flair_template_id": null,
						"is_original_content": false,
						"user_reports": [],
						"secure_media": null,
						"is_reddit_media_domain": false,
						"is_meta": false,
						"category": null,
						"secure_media_embed": {},
						"link_flair_text": null,
						"can_mod_post": false,
						"score": 10759,
						"approved_by": null,
						"thumbnail": "",
						"edited": false,
						"author_flair_css_class": null,
						"author_flair_richtext": [],
						"gildings": {
							"gid_1": 1,
							"gid_2": 2
						},
						"content_categories": null,
						"is_self": true,
						"mod_note": null,
						"created": 1550880522,
						"link_flair_type": "text",
						"wls": 6,
						"banned_by": null,
						"author_flair_type": "text",
						"domain": "self.AskReddit",
						"selftext_html": null,
						"likes": null,
						"suggested_sort": null,
						"banned_at_utc": null,
						"view_count": null,
						"archived": false,
						"no_follow": false,
						"is_crosspostable": false,
						"pinned": false,
						"over_18": false,
						"all_awardings": [
							{
								"is_enabled": true,
								"count": 2,
								"subreddit_id": null,
								"description": "Gold Award",
								"coin_reward": 100,
								"icon_width": 512,
								"icon_url": "https://www.redditstatic.com/gold/awards/icon/gold_512.png",
								"days_of_premium": 7,
								"icon_height": 512,
								"resized_icons": [
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/gold_16.png",
										"width": 16,
										"height": 16
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/gold_32.png",
										"width": 32,
										"height": 32
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/gold_48.png",
										"width": 48,
										"height": 48
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/gold_64.png",
										"width": 64,
										"height": 64
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/gold_128.png",
										"width": 128,
										"height": 128
									}
								],
								"days_of_drip_extension": 0,
								"award_type": "global",
								"coin_price": 500,
								"id": "gid_2",
								"name": "Gold"
							},
							{
								"is_enabled": true,
								"count": 1,
								"subreddit_id": null,
								"description": "Silver Award",
								"coin_reward": 0,
								"icon_width": 512,
								"icon_url": "https://www.redditstatic.com/gold/awards/icon/silver_512.png",
								"days_of_premium": 0,
								"icon_height": 512,
								"resized_icons": [
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/silver_16.png",
										"width": 16,
										"height": 16
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/silver_32.png",
										"width": 32,
										"height": 32
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/silver_48.png",
										"width": 48,
										"height": 48
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/silver_64.png",
										"width": 64,
										"height": 64
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/silver_128.png",
										"width": 128,
										"height": 128
									}
								],
								"days_of_drip_extension": 0,
								"award_type": "global",
								"coin_price": 100,
								"id": "gid_1",
								"name": "Silver"
							}
						],
						"media_only": false,
						"can_gild": false,
						"spoiler": false,
						"locked": false,
						"author_flair_text": null,
						"visited": false,
						"num_reports": null,
						"distinguished": null,
						"subreddit_id": "t5_2qh1i",
						"mod_reason_by": null,
						"removal_reason": null,
						"link_flair_background_color": "",
						"id": "atjc1e",
						"is_robot_indexable": true,
						"report_reasons": null,
						"author": "xXAbyzzXx",
						"num_crossposts": 2,
						"num_comments": 6144,
						"send_replies": true,
						"whitelist_status": "all_ads",
						"contest_mode": false,
						"mod_reports": [],
						"author_patreon_flair": false,
						"author_flair_text_color": null,
						"permalink": "/r/AskReddit/comments/atjc1e/you_can_remove_1_big_company_from_the_world_which/",
						"parent_whitelist_status": "all_ads",
						"stickied": false,
						"url": "https://www.reddit.com/r/AskReddit/comments/atjc1e/you_can_remove_1_big_company_from_the_world_which/",
						"subreddit_subscribers": 22824959,
						"created_utc": 1550851722,
						"media": null,
						"is_video": false
					}
				},
				{
					"kind": "t3",
					"data": {
						"approved_at_utc": null,
						"subreddit": "AskReddit",
						"selftext": "",
						"author_fullname": "t2_9f711",
						"saved": false,
						"mod_reason_title": null,
						"gilded": 0,
						"clicked": false,
						"title": "What controversy does a big corporation hope you forgot about, but you haven't? [Serious]",
						"link_flair_richtext": [
							{
								"e": "text",
								"t": "Serious Replies Only"
							}
						],
						"subreddit_name_prefixed": "r/AskReddit",
						"hidden": false,
						"pwls": 6,
						"link_flair_css_class": "serious",
						"downs": 0,
						"hide_score": false,
						"name": "t3_86fh6j",
						"quarantine": false,
						"link_flair_text_color": "dark",
						"author_flair_background_color": null,
						"subreddit_type": "public",
						"ups": 1658,
						"total_awards_received": 0,
						"media_embed": {},
						"author_flair_template_id": null,
						"is_original_content": false,
						"user_reports": [],
						"secure_media": null,
						"is_reddit_media_domain": false,
						"is_meta": false,
						"category": null,
						"secure_media_embed": {},
						"link_flair_text": "Serious Replies Only",
						"can_mod_post": false,
						"score": 1658,
						"approved_by": null,
						"thumbnail": "",
						"edited": false,
						"author_flair_css_class": null,
						"author_flair_richtext": [],
						"gildings": {},
						"content_categories": null,
						"is_self": true,
						"mod_note": null,
						"created": 1521784775,
						"link_flair_type": "richtext",
						"wls": 6,
						"banned_by": null,
						"author_flair_type": "text",
						"domain": "self.AskReddit",
						"selftext_html": null,
						"likes": null,
						"suggested_sort": null,
						"banned_at_utc": null,
						"view_count": null,
						"archived": true,
						"no_follow": false,
						"is_crosspostable": false,
						"pinned": false,
						"over_18": false,
						"all_awardings": [],
						"media_only": false,
						"can_gild": false,
						"spoiler": false,
						"locked": false,
						"author_flair_text": null,
						"visited": false,
						"num_reports": null,
						"distinguished": null,
						"subreddit_id": "t5_2qh1i",
						"mod_reason_by": null,
						"removal_reason": null,
						"link_flair_background_color": "",
						"id": "86fh6j",
						"is_robot_indexable": true,
						"report_reasons": null,
						"author": "JBSConCarne",
						"num_crossposts": 0,
						"num_comments": 1740,
						"send_replies": true,
						"whitelist_status": "all_ads",
						"contest_mode": false,
						"mod_reports": [],
						"author_patreon_flair": false,
						"author_flair_text_color": null,
						"permalink": "/r/AskReddit/comments/86fh6j/what_controversy_does_a_big_corporation_hope_you/",
						"parent_whitelist_status": "all_ads",
						"stickied": false,
						"url": "https://www.reddit.com/r/AskReddit/comments/86fh6j/what_controversy_does_a_big_corporation_hope_you/",
						"subreddit_subscribers": 22824959,
						"created_utc": 1521755975,
						"media": null,
						"is_video": false
					}
				},
				{
					"kind": "t3",
					"data": {
						"approved_at_utc": null,
						"subreddit": "worldnews",
						"selftext": "",
						"author_fullname": "t2_r0n8ebm",
						"saved": false,
						"mod_reason_title": null,
						"gilded": 0,
						"clicked": false,
						"title": "Nestle says slavery reporting requirements could cost customers",
						"link_flair_richtext": [],
						"subreddit_name_prefixed": "r/worldnews",
						"hidden": false,
						"pwls": 6,
						"link_flair_css_class": null,
						"downs": 0,
						"hide_score": false,
						"name": "t3_9cwyzp",
						"quarantine": false,
						"link_flair_text_color": "dark",
						"author_flair_background_color": null,
						"subreddit_type": "public",
						"ups": 58616,
						"total_awards_received": 0,
						"media_embed": {},
						"author_flair_template_id": null,
						"is_original_content": false,
						"user_reports": [],
						"secure_media": null,
						"is_reddit_media_domain": false,
						"is_meta": false,
						"category": null,
						"secure_media_embed": {},
						"link_flair_text": null,
						"can_mod_post": false,
						"score": 58616,
						"approved_by": null,
						"thumbnail": "",
						"edited": false,
						"author_flair_css_class": null,
						"author_flair_richtext": [],
						"gildings": {},
						"content_categories": null,
						"is_self": false,
						"mod_note": null,
						"created": 1536105723,
						"link_flair_type": "text",
						"wls": 6,
						"banned_by": null,
						"author_flair_type": "text",
						"domain": "smh.com.au",
						"selftext_html": null,
						"likes": null,
						"suggested_sort": null,
						"banned_at_utc": null,
						"view_count": null,
						"archived": true,
						"no_follow": false,
						"is_crosspostable": false,
						"pinned": false,
						"over_18": false,
						"all_awardings": [],
						"media_only": false,
						"can_gild": false,
						"spoiler": false,
						"locked": false,
						"author_flair_text": null,
						"visited": false,
						"num_reports": null,
						"distinguished": null,
						"subreddit_id": "t5_2qh13",
						"mod_reason_by": null,
						"removal_reason": null,
						"link_flair_background_color": "",
						"id": "9cwyzp",
						"is_robot_indexable": true,
						"report_reasons": null,
						"author": "Manu_Jalalala",
						"num_crossposts": 25,
						"num_comments": 4117,
						"send_replies": true,
						"whitelist_status": "all_ads",
						"contest_mode": false,
						"mod_reports": [],
						"author_patreon_flair": false,
						"author_flair_text_color": null,
						"permalink": "/r/worldnews/comments/9cwyzp/nestle_says_slavery_reporting_requirements_could/",
						"parent_whitelist_status": "all_ads",
						"stickied": false,
						"url": "https://www.smh.com.au/politics/federal/nestle-says-slavery-reporting-requirements-could-cost-customers-20180816-p4zy5l.html",
						"subreddit_subscribers": 21289870,
						"created_utc": 1536076923,
						"media": null,
						"is_video": false
					}
				},
				{
					"kind": "t3",
					"data": {
						"approved_at_utc": null,
						"subreddit": "LateStageCapitalism",
						"selftext": "",
						"author_fullname": "t2_278w6n8u",
						"saved": false,
						"mod_reason_title": null,
						"gilded": 0,
						"clicked": false,
						"title": "Nestle is evil",
						"link_flair_richtext": [],
						"subreddit_name_prefixed": "r/LateStageCapitalism",
						"hidden": false,
						"pwls": 0,
						"link_flair_css_class": null,
						"downs": 0,
						"hide_score": false,
						"name": "t3_9twsv1",
						"quarantine": false,
						"link_flair_text_color": "dark",
						"author_flair_background_color": null,
						"subreddit_type": "public",
						"ups": 11852,
						"total_awards_received": 0,
						"media_embed": {},
						"author_flair_template_id": null,
						"is_original_content": false,
						"user_reports": [],
						"secure_media": null,
						"is_reddit_media_domain": true,
						"is_meta": false,
						"category": null,
						"secure_media_embed": {},
						"link_flair_text": null,
						"can_mod_post": false,
						"score": 11852,
						"approved_by": null,
						"thumbnail": "",
						"edited": false,
						"author_flair_css_class": null,
						"author_flair_richtext": [],
						"gildings": {},
						"content_categories": null,
						"is_self": false,
						"mod_note": null,
						"created": 1541301191,
						"link_flair_type": "text",
						"wls": 0,
						"banned_by": null,
						"author_flair_type": "text",
						"domain": "i.redd.it",
						"selftext_html": null,
						"likes": null,
						"suggested_sort": null,
						"banned_at_utc": null,
						"view_count": null,
						"archived": true,
						"no_follow": false,
						"is_crosspostable": false,
						"pinned": false,
						"over_18": false,
						"all_awardings": [],
						"media_only": false,
						"can_gild": false,
						"spoiler": false,
						"locked": false,
						"author_flair_text": null,
						"visited": false,
						"num_reports": null,
						"distinguished": null,
						"subreddit_id": "t5_39qgx",
						"mod_reason_by": null,
						"removal_reason": null,
						"link_flair_background_color": "",
						"id": "9twsv1",
						"is_robot_indexable": true,
						"report_reasons": null,
						"author": "RelevantSwimmer",
						"num_crossposts": 0,
						"num_comments": 129,
						"send_replies": true,
						"whitelist_status": "no_ads",
						"contest_mode": false,
						"mod_reports": [],
						"author_patreon_flair": false,
						"author_flair_text_color": null,
						"permalink": "/r/LateStageCapitalism/comments/9twsv1/nestle_is_evil/",
						"parent_whitelist_status": "no_ads",
						"stickied": false,
						"url": "https://i.redd.it/zct85u7f06w11.png",
						"subreddit_subscribers": 417692,
						"created_utc": 1541272391,
						"media": null,
						"is_video": false
					}
				},
				{
					"kind": "t3",
					"data": {
						"approved_at_utc": null,
						"subreddit": "SkincareAddiction",
						"selftext": "It is with a heavy heart that I cannot buy their products anymore. Goodbye perfect, moisturized skin.\nI think this has been a thing since 2014 but obviously I’m late learning this, so maybe you are too.\n\nHere’s an old thread on why Nestle is Satan [satan thread](https://www.reddit.com/r/OutOfTheLoop/comments/885bk9/why_is_nestle_considered_a_bad_company/?utm_source=share&amp;utm_medium=ios_app), if you care. \n\nI understand if some of you can’t part with our lord and savior Cerave, but does any one have dupes for cerave in the tub or cerave pm or cerave skin renewing night cream.\n\nI guess I’m looking mostly for in the tub dupe, the other two I have options for, but in the tub will be the hardest to say good bye to.\n\nEdit: [zme science article on nestle ](https://www.zmescience.com/science/nestle-company-pollution-children/)",
						"author_fullname": "t2_ifvb575",
						"saved": false,
						"mod_reason_title": null,
						"gilded": 0,
						"clicked": false,
						"title": "[PSA] TIL Cerave is owned by L’Oréal which is 30% owned by Nestle",
						"link_flair_richtext": [],
						"subreddit_name_prefixed": "r/SkincareAddiction",
						"hidden": false,
						"pwls": 6,
						"link_flair_css_class": "PSA",
						"downs": 0,
						"hide_score": false,
						"name": "t3_beh426",
						"quarantine": false,
						"link_flair_text_color": "light",
						"author_flair_background_color": "",
						"subreddit_type": "public",
						"ups": 3417,
						"total_awards_received": 1,
						"media_embed": {},
						"author_flair_template_id": null,
						"is_original_content": false,
						"user_reports": [],
						"secure_media": null,
						"is_reddit_media_domain": false,
						"is_meta": false,
						"category": null,
						"secure_media_embed": {},
						"link_flair_text": "PSA",
						"can_mod_post": false,
						"score": 3417,
						"approved_by": null,
						"thumbnail": "",
						"edited": 1555566770,
						"author_flair_css_class": "notag",
						"author_flair_richtext": [],
						"gildings": {
							"gid_1": 1
						},
						"content_categories": null,
						"is_self": true,
						"mod_note": null,
						"created": 1555588416,
						"link_flair_type": "text",
						"wls": 6,
						"banned_by": null,
						"author_flair_type": "text",
						"domain": "self.SkincareAddiction",
						"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;It is with a heavy heart that I cannot buy their products anymore. Goodbye perfect, moisturized skin.\nI think this has been a thing since 2014 but obviously I’m late learning this, so maybe you are too.&lt;/p&gt;\n\n&lt;p&gt;Here’s an old thread on why Nestle is Satan &lt;a href=\"https://www.reddit.com/r/OutOfTheLoop/comments/885bk9/why_is_nestle_considered_a_bad_company/?utm_source=share&amp;amp;utm_medium=ios_app\"&gt;satan thread&lt;/a&gt;, if you care. &lt;/p&gt;\n\n&lt;p&gt;I understand if some of you can’t part with our lord and savior Cerave, but does any one have dupes for cerave in the tub or cerave pm or cerave skin renewing night cream.&lt;/p&gt;\n\n&lt;p&gt;I guess I’m looking mostly for in the tub dupe, the other two I have options for, but in the tub will be the hardest to say good bye to.&lt;/p&gt;\n\n&lt;p&gt;Edit: &lt;a href=\"https://www.zmescience.com/science/nestle-company-pollution-children/\"&gt;zme science article on nestle &lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
						"likes": null,
						"suggested_sort": null,
						"banned_at_utc": null,
						"view_count": null,
						"archived": false,
						"no_follow": false,
						"is_crosspostable": false,
						"pinned": false,
						"over_18": false,
						"all_awardings": [
							{
								"is_enabled": true,
								"count": 1,
								"subreddit_id": null,
								"description": "Silver Award",
								"coin_reward": 0,
								"icon_width": 512,
								"icon_url": "https://www.redditstatic.com/gold/awards/icon/silver_512.png",
								"days_of_premium": 0,
								"icon_height": 512,
								"resized_icons": [
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/silver_16.png",
										"width": 16,
										"height": 16
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/silver_32.png",
										"width": 32,
										"height": 32
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/silver_48.png",
										"width": 48,
										"height": 48
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/silver_64.png",
										"width": 64,
										"height": 64
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/silver_128.png",
										"width": 128,
										"height": 128
									}
								],
								"days_of_drip_extension": 0,
								"award_type": "global",
								"coin_price": 100,
								"id": "gid_1",
								"name": "Silver"
							}
						],
						"media_only": false,
						"link_flair_template_id": "20306b9c-d010-11e3-b30f-12313b0d3d1d",
						"can_gild": false,
						"spoiler": false,
						"locked": false,
						"author_flair_text": "",
						"visited": false,
						"num_reports": null,
						"distinguished": null,
						"subreddit_id": "t5_2tbbg",
						"mod_reason_by": null,
						"removal_reason": null,
						"link_flair_background_color": "#f79c57",
						"id": "beh426",
						"is_robot_indexable": true,
						"report_reasons": null,
						"author": "_d2gs",
						"num_crossposts": 1,
						"num_comments": 864,
						"send_replies": true,
						"whitelist_status": "all_ads",
						"contest_mode": false,
						"mod_reports": [],
						"author_patreon_flair": false,
						"author_flair_text_color": "dark",
						"permalink": "/r/SkincareAddiction/comments/beh426/psa_til_cerave_is_owned_by_loréal_which_is_30/",
						"parent_whitelist_status": "all_ads",
						"stickied": false,
						"url": "https://www.reddit.com/r/SkincareAddiction/comments/beh426/psa_til_cerave_is_owned_by_loréal_which_is_30/",
						"subreddit_subscribers": 950516,
						"created_utc": 1555559616,
						"media": null,
						"is_video": false
					}
				},
				{
					"kind": "t3",
					"data": {
						"approved_at_utc": null,
						"subreddit": "OutOfTheLoop",
						"selftext": "",
						"author_fullname": "t2_h5wf6",
						"saved": false,
						"mod_reason_title": null,
						"gilded": 0,
						"clicked": false,
						"title": "Why are a lot of people boycotting Nestle?",
						"link_flair_richtext": [
							{
								"e": "text",
								"t": "Answered! "
							}
						],
						"subreddit_name_prefixed": "r/OutOfTheLoop",
						"hidden": false,
						"pwls": 6,
						"link_flair_css_class": "flair c",
						"downs": 0,
						"hide_score": false,
						"name": "t3_3clxv3",
						"quarantine": false,
						"link_flair_text_color": "dark",
						"author_flair_background_color": null,
						"subreddit_type": "public",
						"ups": 2250,
						"total_awards_received": 0,
						"media_embed": {},
						"author_flair_template_id": null,
						"is_original_content": false,
						"user_reports": [],
						"secure_media": null,
						"is_reddit_media_domain": false,
						"is_meta": false,
						"category": null,
						"secure_media_embed": {},
						"link_flair_text": "Answered! ",
						"can_mod_post": false,
						"score": 2250,
						"approved_by": null,
						"thumbnail": "",
						"edited": false,
						"author_flair_css_class": null,
						"author_flair_richtext": [],
						"gildings": {},
						"content_categories": null,
						"is_self": true,
						"mod_note": null,
						"created": 1436425132,
						"link_flair_type": "richtext",
						"wls": 6,
						"banned_by": null,
						"author_flair_type": "text",
						"domain": "self.OutOfTheLoop",
						"selftext_html": null,
						"likes": null,
						"suggested_sort": "confidence",
						"banned_at_utc": null,
						"view_count": null,
						"archived": true,
						"no_follow": true,
						"is_crosspostable": false,
						"pinned": false,
						"over_18": false,
						"all_awardings": [],
						"media_only": false,
						"can_gild": false,
						"spoiler": false,
						"locked": false,
						"author_flair_text": null,
						"visited": false,
						"num_reports": null,
						"distinguished": null,
						"subreddit_id": "t5_2xinb",
						"mod_reason_by": null,
						"removal_reason": null,
						"link_flair_background_color": "",
						"id": "3clxv3",
						"is_robot_indexable": true,
						"report_reasons": null,
						"author": "umadbor",
						"num_crossposts": 0,
						"num_comments": 635,
						"send_replies": true,
						"whitelist_status": "all_ads",
						"contest_mode": false,
						"mod_reports": [],
						"author_patreon_flair": false,
						"author_flair_text_color": null,
						"permalink": "/r/OutOfTheLoop/comments/3clxv3/why_are_a_lot_of_people_boycotting_nestle/",
						"parent_whitelist_status": "all_ads",
						"stickied": false,
						"url": "https://www.reddit.com/r/OutOfTheLoop/comments/3clxv3/why_are_a_lot_of_people_boycotting_nestle/",
						"subreddit_subscribers": 1324647,
						"created_utc": 1436396332,
						"media": null,
						"is_video": false
					}
				},
				{
					"kind": "t3",
					"data": {
						"approved_at_utc": null,
						"subreddit": "AskReddit",
						"selftext": "",
						"author_fullname": "t2_smc6t",
						"saved": false,
						"mod_reason_title": null,
						"gilded": 1,
						"clicked": false,
						"title": "What's an organization that everyone thinks is respectful, but is really just scamming or spreading propaganda?",
						"link_flair_richtext": [],
						"subreddit_name_prefixed": "r/AskReddit",
						"hidden": false,
						"pwls": 6,
						"link_flair_css_class": null,
						"downs": 0,
						"hide_score": false,
						"name": "t3_6sjawn",
						"quarantine": false,
						"link_flair_text_color": "dark",
						"author_flair_background_color": null,
						"subreddit_type": "public",
						"ups": 31810,
						"total_awards_received": 1,
						"media_embed": {},
						"author_flair_template_id": null,
						"is_original_content": false,
						"user_reports": [],
						"secure_media": null,
						"is_reddit_media_domain": false,
						"is_meta": false,
						"category": null,
						"secure_media_embed": {},
						"link_flair_text": null,
						"can_mod_post": false,
						"score": 31810,
						"approved_by": null,
						"thumbnail": "",
						"edited": false,
						"author_flair_css_class": null,
						"author_flair_richtext": [],
						"gildings": {
							"gid_2": 1
						},
						"content_categories": null,
						"is_self": true,
						"mod_note": null,
						"created": 1502283765,
						"link_flair_type": "text",
						"wls": 6,
						"banned_by": null,
						"author_flair_type": "text",
						"domain": "self.AskReddit",
						"selftext_html": null,
						"likes": null,
						"suggested_sort": null,
						"banned_at_utc": null,
						"view_count": null,
						"archived": true,
						"no_follow": false,
						"is_crosspostable": false,
						"pinned": false,
						"over_18": false,
						"all_awardings": [
							{
								"is_enabled": true,
								"count": 1,
								"subreddit_id": null,
								"description": "Gold Award",
								"coin_reward": 100,
								"icon_width": 512,
								"icon_url": "https://www.redditstatic.com/gold/awards/icon/gold_512.png",
								"days_of_premium": 7,
								"icon_height": 512,
								"resized_icons": [
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/gold_16.png",
										"width": 16,
										"height": 16
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/gold_32.png",
										"width": 32,
										"height": 32
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/gold_48.png",
										"width": 48,
										"height": 48
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/gold_64.png",
										"width": 64,
										"height": 64
									},
									{
										"url": "https://www.redditstatic.com/gold/awards/icon/gold_128.png",
										"width": 128,
										"height": 128
									}
								],
								"days_of_drip_extension": 0,
								"award_type": "global",
								"coin_price": 500,
								"id": "gid_2",
								"name": "Gold"
							}
						],
						"media_only": false,
						"can_gild": false,
						"spoiler": false,
						"locked": false,
						"author_flair_text": null,
						"visited": false,
						"num_reports": null,
						"distinguished": null,
						"subreddit_id": "t5_2qh1i",
						"mod_reason_by": null,
						"removal_reason": null,
						"link_flair_background_color": "",
						"id": "6sjawn",
						"is_robot_indexable": true,
						"report_reasons": null,
						"author": "LynxExplorer",
						"num_crossposts": 0,
						"num_comments": 22327,
						"send_replies": true,
						"whitelist_status": "all_ads",
						"contest_mode": false,
						"mod_reports": [],
						"author_patreon_flair": false,
						"author_flair_text_color": null,
						"permalink": "/r/AskReddit/comments/6sjawn/whats_an_organization_that_everyone_thinks_is/",
						"parent_whitelist_status": "all_ads",
						"stickied": false,
						"url": "https://www.reddit.com/r/AskReddit/comments/6sjawn/whats_an_organization_that_everyone_thinks_is/",
						"subreddit_subscribers": 22824959,
						"created_utc": 1502254965,
						"media": null,
						"is_video": false
					}
				},
				{
					"kind": "t3",
					"data": {
						"approved_at_utc": null,
						"subreddit": "AskReddit",
						"selftext": "",
						"author_fullname": "t2_78pi6",
						"saved": false,
						"mod_reason_title": null,
						"gilded": 0,
						"clicked": false,
						"title": "What is a company that you refuse to support? What is your reason for this?",
						"link_flair_richtext": [],
						"subreddit_name_prefixed": "r/AskReddit",
						"hidden": false,
						"pwls": 6,
						"link_flair_css_class": null,
						"downs": 0,
						"hide_score": false,
						"name": "t3_5b1127",
						"quarantine": false,
						"link_flair_text_color": "dark",
						"author_flair_background_color": null,
						"subreddit_type": "public",
						"ups": 16117,
						"total_awards_received": 0,
						"media_embed": {},
						"author_flair_template_id": null,
						"is_original_content": false,
						"user_reports": [],
						"secure_media": null,
						"is_reddit_media_domain": false,
						"is_meta": false,
						"category": null,
						"secure_media_embed": {},
						"link_flair_text": null,
						"can_mod_post": false,
						"score": 16117,
						"approved_by": null,
						"thumbnail": "",
						"edited": false,
						"author_flair_css_class": null,
						"author_flair_richtext": [],
						"gildings": {},
						"content_categories": null,
						"is_self": true,
						"mod_note": null,
						"created": 1478253933,
						"link_flair_type": "text",
						"wls": 6,
						"banned_by": null,
						"author_flair_type": "text",
						"domain": "self.AskReddit",
						"selftext_html": null,
						"likes": null,
						"suggested_sort": null,
						"banned_at_utc": null,
						"view_count": null,
						"archived": true,
						"no_follow": false,
						"is_crosspostable": false,
						"pinned": false,
						"over_18": false,
						"all_awardings": [],
						"media_only": false,
						"can_gild": false,
						"spoiler": false,
						"locked": false,
						"author_flair_text": null,
						"visited": false,
						"num_reports": null,
						"distinguished": null,
						"subreddit_id": "t5_2qh1i",
						"mod_reason_by": null,
						"removal_reason": null,
						"link_flair_background_color": "",
						"id": "5b1127",
						"is_robot_indexable": true,
						"report_reasons": null,
						"author": "Bystronicman08",
						"num_crossposts": 0,
						"num_comments": 21920,
						"send_replies": true,
						"whitelist_status": "all_ads",
						"contest_mode": false,
						"mod_reports": [],
						"author_patreon_flair": false,
						"author_flair_text_color": null,
						"permalink": "/r/AskReddit/comments/5b1127/what_is_a_company_that_you_refuse_to_support_what/",
						"parent_whitelist_status": "all_ads",
						"stickied": false,
						"url": "https://www.reddit.com/r/AskReddit/comments/5b1127/what_is_a_company_that_you_refuse_to_support_what/",
						"subreddit_subscribers": 22824959,
						"created_utc": 1478225133,
						"media": null,
						"is_video": false
					}
				},
				{
					"kind": "t3",
					"data": {
						"approved_at_utc": null,
						"subreddit": "PewdiepieSubmissions",
						"selftext": "",
						"author_fullname": "t2_2w85w02u",
						"saved": false,
						"mod_reason_title": null,
						"gilded": 0,
						"clicked": false,
						"title": "The 3 most hated companies",
						"link_flair_richtext": [],
						"subreddit_name_prefixed": "r/PewdiepieSubmissions",
						"hidden": false,
						"pwls": 0,
						"link_flair_css_class": null,
						"downs": 0,
						"hide_score": false,
						"name": "t3_bdozxx",
						"quarantine": false,
						"link_flair_text_color": "dark",
						"author_flair_background_color": null,
						"subreddit_type": "public",
						"ups": 12437,
						"total_awards_received": 0,
						"media_embed": {},
						"author_flair_template_id": null,
						"is_original_content": false,
						"user_reports": [],
						"secure_media": null,
						"is_reddit_media_domain": true,
						"is_meta": false,
						"category": null,
						"secure_media_embed": {},
						"link_flair_text": null,
						"can_mod_post": false,
						"score": 12437,
						"approved_by": null,
						"thumbnail": "",
						"edited": false,
						"author_flair_css_class": null,
						"author_flair_richtext": [],
						"gildings": {},
						"content_categories": null,
						"is_self": false,
						"mod_note": null,
						"created": 1555412752,
						"link_flair_type": "text",
						"wls": 0,
						"banned_by": null,
						"author_flair_type": "text",
						"domain": "i.redd.it",
						"selftext_html": null,
						"likes": null,
						"suggested_sort": "top",
						"banned_at_utc": null,
						"view_count": null,
						"archived": false,
						"no_follow": false,
						"is_crosspostable": false,
						"pinned": false,
						"over_18": false,
						"all_awardings": [],
						"media_only": false,
						"can_gild": false,
						"spoiler": false,
						"locked": false,
						"author_flair_text": null,
						"visited": false,
						"num_reports": null,
						"distinguished": null,
						"subreddit_id": "t5_3m0tc",
						"mod_reason_by": null,
						"removal_reason": null,
						"link_flair_background_color": "",
						"id": "bdozxx",
						"is_robot_indexable": true,
						"report_reasons": null,
						"author": "jasons060902",
						"num_crossposts": 0,
						"num_comments": 167,
						"send_replies": true,
						"whitelist_status": "no_ads",
						"contest_mode": false,
						"mod_reports": [],
						"author_patreon_flair": false,
						"author_flair_text_color": null,
						"permalink": "/r/PewdiepieSubmissions/comments/bdozxx/the_3_most_hated_companies/",
						"parent_whitelist_status": "no_ads",
						"stickied": false,
						"url": "https://i.redd.it/lj6criyiljs21.jpg",
						"subreddit_subscribers": 1553597,
						"created_utc": 1555383952,
						"media": null,
						"is_video": false
					}
				}
			],
			"before": null
		}
	}
}


class ProductDetails extends React.Component {

	tabs = ["Top Stories", "Local Alternatives"];
	state = {
		activeTab: "Top Stories"
	}

	tabClickHandlerFactory(tab) {
		return (event) => {
			this.setState({activeTab: tab});
			console.log(tab);
		}
	}

	render() {
		console.log(this.props)

		const product = this.props.product || propsProduct.product;
		const company = product.BSIN;

		const companyClickHandler = () => {
			window.open(company.link, "_blank");
		}

		const tabComponents = this.tabs.map((el, idx) => (
			<div className={`tab ${el === this.state.activeTab && "active"}`} onClick={this.tabClickHandlerFactory(el)} key={idx}>{el}</div>
		))

		const imgSrc = company.name == "Nestlé" ? nestleLogo : company.img;

		return (
			<div className="productDetails" >
				<div className="innerContainer">

					{/*Company Header*/}
					<div className="companyHeader" onClick={companyClickHandler}>
						<div className="companyID">
							<div className="logo">
								<img src={imgSrc} alt="company logo"/>
							</div>
							<div className="name">
								{company.name}
							</div>
						</div>
						<div className="morality">
							<span className="title">Morality <br/>Score</span>
							<span className="score">32%</span>
						</div>
					</div>


					{/*Product Section*/}
					<div className="productDescription">
						<img className="productImg" src={product.img} alt="product image"/>
						<div className="name">
							<div className="header">
								Scanned Product
							</div>
							{product.name}
						</div>
					</div>


					{/*Company Info*/}
					<div className="companyInfo">
						<div className="foundingInfo">
							<div className="header">Founded in</div>
							1866
						</div>

						<div className="ceo">
							<div className="header">Current CEO</div>
							Ulf Mark Schneider
						</div>
					</div>


					{/*Tabs*/}
					<div className="tabs">
						{tabComponents}
					</div>

					{this.state.activeTab == "Local Alternatives" && <AlternativesList/>}



				</div>
			</div>
		);
	}
}

export default ProductDetails;
